### ISSUE TITLE
Range is supposed to be half-open

### ISSUE THREAD

**Issue by chris-morgan** [ChrisBuchholz/accord#8]
`Range` is defined in Rust as half-open: so `12..127` means “at least 12, and less than 127”. In your validators you’ve implemented it with incorrect semantics, treating it as an inclusive range, which is instead `12...127` (and [experimental](https://github.com/rust-lang/rust/issues/28237)).

**Comment by ChrisBuchholz** [comment]
I wasn't aware of that when I Implemented it, but you're correct.

What our situation is:

* validators `range` and `length` uses wrong semantics for `std::ops::Range`
* neither validator actually break since they are not using the `Range`s as opposed to just using the `range.start` and `range.end` property on the `Range`.

Since inclusive ranges are experimental our options, as I see them, are:

* let things be as they are since *only* semantics are broken, code still works as it should *(my least favorite solution)*
* add the `inclusive_range_syntax` feature to the crate and fix the semantics in the examples and tests, which might not be a big problem since accord is requiring nightly anyways
* dont use ranges, use `a,b`-variables instead

I'm not sure what to do right now. Will have to think about it. What are your thoughts, @chris-morgan?

**Comment by ChrisBuchholz** [comment]
I added some tests to show that `range` and `length` works as *I* intended them (although with wrong semantics): https://github.com/ChrisBuchholz/accord/commit/131e31c2cbd3bf1c278b5d789fcc65fb288a8f7e

**Comment by chris-morgan** [comment]
Inclusive range syntax seems to be fairly unstable, and it’s quite possible that it will change syntax notably. What I observe is that other Rust APIs that could logically take inclusive ranges tend instead to take two arguments.

Then again, allowing both `length(5)` and `length(5...8)` is nice, but you can’t make functions variadic so `length(5, 8)` can’t work.

**Comment by ChrisBuchholz** [comment]
@chris-morgan: I brought Accord back to stable yesterday and are gonna add unstable features to Accord via feature gates. I think the solution simply is to use inclusive range on unstable and leave stable as it is right now, although its quite ugly with the half-open range on stable that isn't actually half-open.

**Comment by chris-morgan** [comment]
`length(5, 8)` is better than `length(5..8)` if that means [5, 8] rather than [5, 8). Bad semantics are damaging and confusing.

**Comment by ChrisBuchholz** [comment]
@chris-morgan: you are right, the better solution is that the stable version of length and range takes two variables, and the nightly version take inclusive range.

**Comment by ChrisBuchholz** [comment]
@chris-morgan: I finally got around to fix it. Now stable uses `a, b`-variables and on nightly, one can use the feature *inclusive_range* to enable use of `RangeInclusive<T>`, which in fact the two unstable examples bundled with Accord does.
